### ISSUE TITLE
`choice` and `or` combinators do not work correctly with `string`

### ISSUE THREAD

**Issue by franza** [typemeta/funcj#22]
Hello. First, an amazing library, I am a big fan. Thanks for your work.

I have an issue when I am trying to `choice` between different options of `string`. Consider the next example:

```java
    public Parser<Chr, String> day() {
        return choice(
                string("today"),
                string("tomorrow")
        );
    }

// tests

    @Test
    public void testDay() {
        Result<Chr, String> res = day().parse(Input.of("tomorrow"));
        String result = res.getOrThrow();
        assertEquals(result, "tomorrow");
    }
```

Getting the error here:
```
java.lang.RuntimeException: Failure at position 2, expected=t

	at org.typemeta.funcj.parser.Result$FailureOnExpected.getOrThrow(Result.java:253)
// blabla java stack trace
```

I suppose that the test should go green here, as parser should fail on trying to compare to "today" and fallback to "tomorrow". What I think is happening is that parser fails on first option and dies there without picking the next option. Is there a workaround or fix for this problem?

**UPD**
In fact, the test passed for parser `choice(string("yesterday"), string("tomorrow"))`. Now I think it has something to do with the first characters of variants.

**Comment by jon-hanson** [comment]
Hi, thanks for your comments. The error is due to the fact that the parser is for LL(1) grammars, meaning grammars that can be parsed by only looking 1 character ahead (i.e. at the next char) at each step. Your grammar breaks this as the two alternative words share the first 2 characters ("to"). This means the parser has to look 3 characters ahead to determine which of the two words it is.

The simplest way to address this is to parse the common prefix first and then parse the remaining suffix as a choice:

    public static final Parser<Chr, String> day =
            string("to")
                    .andR(choice(
                            string("day").andR(pure("today")),
                            string("morrow").andR(pure("tomorrow"))
                    ));

I hope that helps.

**Comment by franza** [comment]
Okay, now I get it right. Thanks for explanation about LL(1) grammar, I am usually ignoring such info when reading documentation :) Thanks for the help!
