### ISSUE TITLE
Partial parsing fails

### ISSUE THREAD

**Issue by mark-christiaens** [typemeta/funcj#26]
Consider this test:
```
@Test
	public void partialParse() {
		Text.string("ab").many().apply(Input.of("ababa")).getOrThrow();
	}
```

I'm trying to extract the matching substring `"abab"` and leave a remaining `"a"` in the `Input` (hence the use of the `apply` method and not the `parse` method).  However, this code fails with:
```
java.lang.RuntimeException: Failure at position 5, expected=a
	at org.typemeta.funcj.parser.Result$FailureOnExpected.getOrThrow(Result.java:252)
...
```
Replacing the final `a` with `c` results in success
```
@Test
	public void partialParse() {
		Text.string("ab").many().apply(Input.of("ababc")).getOrThrow();
	}
```
I suspect that the root cause is in:
```
    default Parser<I, IList<A>> many() {
        if (acceptsEmpty().apply()) {
            throw new RuntimeException("Cannot construct a many parser from one that accepts empty");
        }
        // We use an iterative implementation, in favour of a more concise recursive solution,
        // for performance, and to avoid StackOverflowExceptions.
        return new ParserImpl<I, IList<A>>(LTRUE, this.firstSet()) {
            @Override
            public Result<I, IList<A>> apply(Input<I> in, SymSet<I> follow) {
                IList<A> acc = IList.of();
                final SymSet<I> follow2 = follow.union(Parser.this.firstSet().apply());
                while (true) {
                    if (!in.isEof()) {
                        final I i = in.get();
                        if (Parser.this.firstSet().apply().matches(i)) {
                            final Result<I, A> r = Parser.this.apply(in, follow2);
                            if (r.isSuccess()) {
                                final Result.Success<I, A> succ = (Result.Success<I, A>) r;
                                acc = acc.add(succ.value());
                                in = succ.next();
                                continue;
                            } else {
                                return ((Result.Failure<I, A>)r).cast();
                            }
                        }
                    }
                    return Result.success(acc.reverse(), in);
                }
            }
        };
    }
```
IIUIC, this code will continue to repeat the parsing step as long as `Parser.this.firstSet().apply().matches(i)`.  In the example, the last iteration fails because `"a"` doesn't match the entire pattern `"ab"`.  What is more, this results in returning a failure.  I would have expected to return the successful previous iterations (excluding the last failed attempt)?

Maybe I'm completely off-base here.  If so, could you give an example of a partial parse?

**Comment by jon-hanson** [comment]
It's an interesting point. The basic issue is that funcj.parser is a parser for LL(1) grammars, which only allows the parser to look 1 symbol ahead when parsing. This implies the parser doesn't support backtracking as it can always determine the next rule from the next symbol.

The parser decorates each parse rule with the set of inital symbols that that rule accepts (aka the "first set"). The parser then uses this information to determine which parse rule to select next by inspecting the next symbol and choosing the rule that has that symbol in its first set.

The upshot of this is that once the parser starts a rule it has to commit to it - either the rule succeeds or it's a parse failure.

The many combinator therefore expects the parse rule that it operates on to either completely succeed or to not be applicable on each iteration. In your example, once the parser encounters the second "a" it commits to the rule to parse "ab", meaning that when the rule fails it can't backtrack and the many rule fails rather than returning a partial result.

So, I think the what you're seeing is expected behaviour. If you tried to use your many("ab") rule as part of a wider grammar where that rule could legitmately be followed by an "a" (meaning that "ababa" were a valid substring) then the grammar wouldn't be LL(1) because the parser would have to look further ahead than the next symbol to determine which rule to apply when it encounters the last "a".

I hope that helps explain the issue.

**Comment by mark-christiaens** [comment]
Interesting.  So, IIUIC then it's not possible to implement a regular expression Kleene star operator with these limitations.

**Comment by jon-hanson** [comment]
Not sure what you mean. As I understand it, the many combinator is providing the same functionality as the Kleene star operator, and, as I explained above, you can use many as long as the resultant grammar is LL(1).

**Comment by mark-christiaens** [comment]
I think I mean that regular expressions must have a farther lookahead than 1 to be able to do a partial match of regular expression `(ab)*` in the source string `ababa`.  Using a regular expression, you would be able to identify the prefix `abab` as a match.   A regular expression would first match `abab` then attempt the final `a` and notice that there is no following `b`.  Then it would give up on the final `a`.  But I guess that is lookahead 2.

**Comment by jon-hanson** [comment]
You can convert a regular expression into an LL(1) grammar by first translating it into a DFA - the DFA state transitions can then be translated into corresponding parse rules. In your example it would mean taking the A -> (ab)* rule and splitting it into multiple mutually recursive rules.
