### ISSUE TITLE
Question: choice not taking alternate paths

### ISSUE THREAD

**Issue by matozoid** [typemeta/funcj#3]
Hello! Thanks for your nice library.

I have a question, when I execute this:
```java
final Parser<Chr, String> p = choice(string("128").or(string("16")).or(string("1")));
System.out.println(p.parse(Input.of("128")));
System.out.println(p.parse(Input.of("16")));
System.out.println(p.parse(Input.of("1")));
```
the output is:
```
Success{value=128, next=StringInput{3,data="EOF"}
FailureOnExpected{input=StringInput{1,data="6", expected=1}
FailureOnExpected{input=StringInput{1,data="EOF", expected=1}
```
I expected it to pass all three, because the choice should try each option in turn. It seems to fail because the options all start with "1", and only tries the first one? What am I doing wrong?

**Comment by jon-hanson** [comment]
Firstly, you don't need to use both the `choice` and `or` combinators at the same time. `choice(A, B, C)` is a short-hand for `A.or(B).or(C)`. I.e. you can define p either using `choice`:
```Java
final Parser<Chr, String> p = choice(string("128"), string("16"), string("1"));
```
or using `or`:
```Java
final Parser<Chr, String> p = string("128").or(string("16")).or(string("1"));
```
(both are equivalent)

Next, your grammar isn't LL(1) because for the ruke:

```
P = "128" | "16" | "1"
```

we need to look 2 characters ahead when a "1" is encountered - in order to resolve between the 3 rules that begin with a "1". To resolve this you need to restructure the rule so that it first parses the "1" and then attempts to parse the remainder:


```
P = "1" R
R = "28" | "6" | <eof>
```

Using the funcj parser this would like something like this:

 ```Java
final Parser<Chr, String> p =
        string("1")
                .and(
                        choice(
                                string("28"),
                                string("6"),
                                Combinators.<Chr>eof().map(u -> "")
                        )
                ).map(a -> b -> a + b);
```

or (slightly cleaner):

```Java
final Parser<Chr, String> p =
        string("1")
                .andR(
                        choice(
                                string("28").map(u -> "128"),
                                string("6").map(u -> "16"),
                                Combinators.<Chr>eof().map(u -> "1")
                        )
                );
```
This now gives the desired result:
```
Success{value=128, next=StringInput{3,data="EOF"}
Success{value=16, next=StringInput{2,data="EOF"}
Success{value=1, next=StringInput{1,data="EOF"}
```
Hope that helps.

**Comment by matozoid** [comment]
Thanks for the help, I get it now.
